import { Inter } from "next/font/google";
import "./globals.css";
import CountProvider from "./components/Context/CountProvider";
import UserDetailsProvider from "./components/Context/UserDetailsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDetailsProvider>
          <CountProvider>{children}</CountProvider>
        </UserDetailsProvider>
      </body>
    </html>
  );
}
