import { Inter } from "next/font/google";
import "./globals.css";
import UserDetailsProvider from "./components/userDetailsProvider/UserDetailsProvider";
import CountProvider from "./components/Context/CountProvider";
import User1DetailsProvider from "./components/Context/User1DetailsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDetailsProvider>
          <User1DetailsProvider>
          <CountProvider>{children}</CountProvider>
          </User1DetailsProvider>
        </UserDetailsProvider>
      </body>
    </html>
  );
}
